services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tgreddit
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - TGRHB_DB_SOURCE=postgresql://root:password@postgres:5432/tgrhb_db?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]