// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Config struct {
	ConfigType string     `json:"config_type"`
	Data       ConfigData `json:"data"`
}

type Post struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostImage struct {
	ID    int64  `json:"id"`
	Post  string `json:"post"`
	Url   string `json:"url"`
	IsGif bool   `json:"is_gif"`
}

type PostVideo struct {
	ID       int64  `json:"id"`
	Post     string `json:"post"`
	Height   int32  `json:"height"`
	Width    int32  `json:"width"`
	Duration int32  `json:"duration"`
	Url      string `json:"url"`
}

type PostsCount struct {
	Count int64 `json:"count"`
}
