// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: post_videos.sql

package db

import (
	"context"
)

const createPostVideo = `-- name: CreatePostVideo :one
INSERT INTO post_videos (
    post,
    height,
    width,
    duration,
    url,
    audio_url
) VALUES (
$1, $2, $3, $4, $5, $6
) RETURNING id, post, height, width, duration, url, tg_file_id, audio_url
`

type CreatePostVideoParams struct {
	Post     string `json:"post"`
	Height   int32  `json:"height"`
	Width    int32  `json:"width"`
	Duration int32  `json:"duration"`
	Url      string `json:"url"`
	AudioUrl string `json:"audio_url"`
}

func (q *Queries) CreatePostVideo(ctx context.Context, arg CreatePostVideoParams) (PostVideo, error) {
	row := q.db.QueryRow(ctx, createPostVideo,
		arg.Post,
		arg.Height,
		arg.Width,
		arg.Duration,
		arg.Url,
		arg.AudioUrl,
	)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.Post,
		&i.Height,
		&i.Width,
		&i.Duration,
		&i.Url,
		&i.TgFileID,
		&i.AudioUrl,
	)
	return i, err
}

const getVideosByPost = `-- name: GetVideosByPost :many
SELECT id, post, height, width, duration, url, tg_file_id, audio_url FROM post_videos
WHERE post = $1 LIMIT 5
`

func (q *Queries) GetVideosByPost(ctx context.Context, post string) ([]PostVideo, error) {
	rows, err := q.db.Query(ctx, getVideosByPost, post)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostVideo{}
	for rows.Next() {
		var i PostVideo
		if err := rows.Scan(
			&i.ID,
			&i.Post,
			&i.Height,
			&i.Width,
			&i.Duration,
			&i.Url,
			&i.TgFileID,
			&i.AudioUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoFileId = `-- name: SetVideoFileId :exec
UPDATE post_videos
SET tg_file_id = $1
WHERE post = $2
`

type SetVideoFileIdParams struct {
	TgFileID string `json:"tg_file_id"`
	Post     string `json:"post"`
}

func (q *Queries) SetVideoFileId(ctx context.Context, arg SetVideoFileIdParams) error {
	_, err := q.db.Exec(ctx, setVideoFileId, arg.TgFileID, arg.Post)
	return err
}
